#!/bin/bash
# 批量执行指令的脚本
set -e  # 关键：任意指令失败则脚本立即退出（可选，增强安全性）

echo dpjdg 模型
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_1-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_1-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_1-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_1-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_1-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_1-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_1-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_1-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_1-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_1-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_5-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_5-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_5-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_5-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_5-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_5-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_5-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_5-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_5-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_5-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_10-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_10-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_10-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_10-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_10-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_10-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_10-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_10-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_10-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T1_10-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_1-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_1-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_1-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_1-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_1-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_1-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_1-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_1-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_1-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_1-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_5-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_5-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_5-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_5-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_5-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_5-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_5-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_5-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_5-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_5-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_10-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_10-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_10-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_10-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_10-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_10-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_10-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_10-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_10-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T2_10-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_1-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_1-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_1-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_1-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_1-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_1-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_1-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_1-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_1-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_1-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_5-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_5-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_5-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_5-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_5-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_5-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_5-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_5-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_5-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_5-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_10-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_10-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_10-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_10-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_10-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_10-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_10-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_10-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_10-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T3_10-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_1-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_1-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_1-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_1-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_1-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_1-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_1-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_1-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_1-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_1-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_5-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_5-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_5-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_5-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_5-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_5-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_5-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_5-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_5-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_5-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_10-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_10-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_10-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_10-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_10-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_10-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_10-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_10-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_10-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_phm_T4_10-10.yaml

python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_1-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_1-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_1-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_1-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_1-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_1-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_1-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_1-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_1-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_1-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_5-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_5-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_5-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_5-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_5-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_5-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_5-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_5-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_5-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_5-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_10-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_10-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_10-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_10-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_10-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_10-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_10-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_10-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_10-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T5_10-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_1-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_1-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_1-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_1-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_1-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_1-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_1-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_1-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_1-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_1-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_5-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_5-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_5-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_5-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_5-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_5-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_5-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_5-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_5-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_5-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_10-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_10-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_10-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_10-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_10-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_10-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_10-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_10-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_10-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T6_10-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_1-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_1-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_1-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_1-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_1-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_1-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_1-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_1-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_1-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_1-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_5-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_5-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_5-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_5-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_5-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_5-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_5-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_5-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_5-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_5-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_10-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_10-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_10-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_10-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_10-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_10-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_10-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_10-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_10-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T7_10-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_1-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_1-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_1-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_1-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_1-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_1-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_1-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_1-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_1-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_1-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_5-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_5-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_5-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_5-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_5-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_5-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_5-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_5-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_5-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_5-10.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_10-1.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_10-2.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_10-3.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_10-4.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_10-5.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_10-6.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_10-7.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_10-8.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_10-9.yaml
python -m src.main --configs src/configs/dpjdg/dpjdg_pu_T8_10-10.yaml

echo 关机
shutdown -h now