
BASE: ../mcpdg_ablate.yaml

data:
  train_h5: /root/data/phm-spur/phm-spur_T1_5/train.h5
  test_h5: /root/data/phm-spur/phm-spur_T1_5/test.h5
  dataset_name: phm          # phm / pu
  num_classes: 8

model:
  use_linear_head: true
  use_dynamic_proto: false
  use_proto_cls: false
  use_align_loss: false
  use_pcl_loss: false
  use_meta_loss: true


output:
  exp_name: mcpdg-a0_phm_T5_300-5




