
BASE: ../mcpdg.yaml

data:
  train_h5: /root/data/phm-spur/phm-spur_T2_20/train.h5
  test_h5: /root/data/phm-spur/phm-spur_T2_20/test.h5
  dataset_name: phm
  num_classes: 8

output:
  exp_name: mcpdg_phm_T2_20
