BASE: base.yaml

data:
  train_h5: data/PHM_spur/PHM_spur8_T1_300-1/train.h5
  test_h5: data/PHM_spur/PHM_spur8_T1_300-1/test.h5
  dataset_name: phm
  num_classes: 8

method:
  name: darm

model:
  feature_mode: freq
  freq_backbone_name: resnet1d18
  tf_backbone_name: resnet18
  freq_in_channels: 1
  tf_in_channels: 1
  freq_pretrained: false
  tf_pretrained: false
  classifier_dropout: 0.0
  backbone_kwargs:
    norm: bn
    act: elu

  darm_iti_weight: 0.1
  darm_ptp_weight: 0.1
  darm_margin: 1.0
  darm_feature_normalize: true


output:
  root: outputs
  exp_name: darm_phm_T1_300-1