BASE: base.yaml

method:
  name: dpjdg

model:
  feature_mode: freq
  freq_backbone_name: resnet1d18
  freq_in_channels: 1
  freq_pretrained: false
  classifier_dropout: 0.0
  backbone_kwargs:
    norm: bn
    act: elu

  dpjdg_consistency_weight: 0.5
  dpjdg_mmd_weight: 0.5
  dpjdg_aug_noise_std: 0.02
  dpjdg_mask_ratio: 0.05
  dpjdg_rbf_gamma: 1.0

loss:
  use_class_weights: true  # 类别不平衡时建议开启

output:
  exp_name: dpjdg_freq_resnet1d18
