BASE: base.yaml

method:
  name: irm

model:
  feature_mode: freq
  freq_backbone_name: resnet1d18
  tf_backbone_name: resnet18
  freq_in_channels: 1
  tf_in_channels: 1
  freq_pretrained: false
  tf_pretrained: false
  classifier_dropout: 0.0
  irm_lambda: 1.0
  irm_penalty_anneal_iters: 0
  backbone_kwargs:
    norm: bn
    act: elu

output:
  exp_name: irm_freq_resnet1d18
