BASE: base.yaml

method:
  name: mldg

model:
  feature_mode: freq
  freq_backbone_name: resnet1d18
  freq_in_channels: 1
  freq_pretrained: false
  classifier_dropout: 0.0
  backbone_kwargs:
    norm: bn
    act: elu

  # MLDG-specific
  mldg_beta: 1.0
  mldg_inner_lr: 0.01
  mldg_meta_test_domains: 1
  mldg_first_order: false
  mldg_split_seed: 42

loss:
  name: ce
  use_class_weights: false
  gamma: 2.0


sampler:
  enabled: true
  name: meta_domain_batch_sampler
  domains_per_batch: 3
  samples_per_domain: null
  shuffle: true
  drop_last: false
