name: dsfsfd

encoders:
  tf:
    blockdim: [64, 64, 128, 256, 512]
    feature_trans: true
  de:
    blockdim: [32, 32, 64, 128, 256]
    feature_trans: true
  fft:
    blockdim: [16, 16, 32, 64, 128]
    feature_trans: true

loss:
  TF_weight: 0.25
  DE_weight: 0.60
  FFT_weight: 0.15
