model:
  name: pcdg

  modalities:
    use_time: false    # DE_time (512)
    use_fft:  true    # FFT_data (256)
    use_tf:   false    # jpg 时频图

  emb_dim: 256
  proj_dim: 128
  fft_in_dim: 256

  mixstyle:
    p: 0.5
    alpha: 0.3

  continual:
    enable: true
    num_classes: 10     # 你选的 1健康+9故障
    momentum: 0.9

  loss:
    w_proto: 1.0
    w_supcon: 0.2
    w_drift: 0.1
    temperature: 0.07
