
BASE: ../vrex.yaml

data:
  train_h5: data/PHM_spur/PHM_spur8_T6_300-10/train.h5
  test_h5: data/PHM_spur/PHM_spur8_T6_300-10/test.h5
  dataset_name: phm
  num_classes: 8

output:
  exp_name: vrex_phm_T6_300-10
