
BASE: ../dpjdg.yaml

data:
  train_h5: data/PHM_spur/PHM_spur8_T8_300-10/train.h5
  test_h5: data/PHM_spur/PHM_spur8_T8_300-10/test.h5
  dataset_name: phm
  num_classes: 8

output:
  exp_name: dpjdg_phm_T8_300-10
