
BASE: ../dpjdg.yaml

data:
  train_h5: data/CWRU_12k_DE/CWRU_T1_300-5/train.h5
  test_h5: data/CWRU_12k_DE/CWRU_T1_300-5/test.h5
  dataset_name: cwru
  num_classes: 10

output:
  exp_name: dpjdg_cwru_T1_300-5
