BASE: ../pu_config.yaml

# 任务6：0，1，3 -> 2 -> 2
split:
  # 源域工况
  source_conditions:
    - "N09_M07_F10"
    - "N15_M01_F10"
    - "N15_M07_F10"
  # 目标域工况
  target_condition: "N15_M07_F04"

sampling:
  source:
    normal_per_domain: 300
    fault_per_class_per_domain: 10


output:
  task_name: "PU_T6_10"