BASE: ../cwru_config.yaml

split:
  # 4 个工况域
  # 任务4：1，2，3 -> 0
  source_conditions:
    - "1HP"
    - "2HP"
    - "3HP"
  target_condition: "0HP"

sampling:
  # 源域（训练集）抽样数
  source:
    normal_per_domain: 300
    fault_per_class_per_domain: 1

output:
  output_dir: "data/CWRU_12k_DE"
  task_name: "CWRU_T4_300-1"