
BASE: ../mldg.yaml

data:
  train_h5: /root/data/phm-spur/phm-spur_T1_1/train.h5
  test_h5: /root/data/phm-spur/phm-spur_T1_1/test.h5
  dataset_name: phm
  num_classes: 8

output:
  exp_name: mldg_phm_T1_1
