BASE: ../phm_super8_config.yaml
# H1:"30hz_High"
# H2:"35hz_High"
# H3:"40hz_High"
# H4:"45hz_High"
# 任务8：1，2，3 -> 0


split:
  source_conditions:
    - "35hz_High"
    - "40hz_High"
    - "45hz_High"
  target_condition: "30hz_High"

sampling:
  source:
    normal_per_domain: 300
    fault_per_class_per_domain: 20

output:
  output_dir: "data/PHM_spur"
  task_name: "PHM_spur8_T8_300-20"